(() => {
  const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
  const STORAGE_KEY='state-v65-sessions', MODE_KEY='state-v65-mode';
  const formulas=window.STATE_FORMULAS;
  let selectedState=null,current=formulas.overwhelmed,mode=localStorage.getItem(MODE_KEY)||'ritual',selectedSeconds=60,remaining=60,total=60,timer=null,paused=false,startedAt=null,status='idle',wakeLock=null,currentSessionId=null,pendingFollowupId=null;
  const screens=$$('.screen');
  const loadSessions=()=>{try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]')}catch{return[]}};
  const saveSessions=items=>localStorage.setItem(STORAGE_KEY,JSON.stringify(items.slice(-300)));
  const toast=msg=>{const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),2400)};
  const setDock=id=>$$('[data-dock]').forEach(b=>b.classList.toggle('active',b.dataset.dock===id));
  const show=(id,label)=>{screens.forEach(s=>s.classList.toggle('hidden',s.id!==id));$('#chapter').textContent='DAILY DOSE / '+label;setDock(id==='patterns'?'patterns':'arrival');window.scrollTo({top:0,behavior:'smooth'});if(id==='patterns')renderPatterns()};
  const format=s=>`${String(Math.floor(Math.max(0,s)/60)).padStart(2,'0')}:${String(Math.max(0,s)%60).padStart(2,'0')}`;
  const timeBucket=date=>{const h=new Date(date).getHours();return h<12?'morning':h<18?'afternoon':'evening'};
  const avg=values=>values.length?values.reduce((a,b)=>a+b,0)/values.length:null;
  const id=()=>`${Date.now()}-${Math.random().toString(16).slice(2)}`;

  function setMode(next){mode=next;localStorage.setItem(MODE_KEY,mode);$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode))}
  $$('[data-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));setMode(mode);

  $$('.state-card').forEach(card=>card.addEventListener('click',()=>{selectedState=card.dataset.state;current=formulas[selectedState];$$('.state-card').forEach(c=>{c.classList.toggle('selected',c===card);c.setAttribute('aria-pressed',c===card?'true':'false')});$('#otherInput').classList.toggle('show',selectedState==='other');$('#selectionHint').textContent=`Selected: ${card.querySelector('strong').textContent}`;$('#continueButton').disabled=false;document.documentElement.style.setProperty('--accent',current.accent);document.documentElement.style.setProperty('--accent2',current.accent2);if(navigator.vibrate)navigator.vibrate(12)}));
  $('#continueButton').addEventListener('click',()=>{if(!selectedState)return;updateFormula();show(mode==='quick'?'recommendation':'recognition',mode==='quick'?'ONE CONDITION':'RECOGNITION')});
  $('#backToStates').addEventListener('click',()=>show('arrival','ARRIVE'));$('#seeCondition').addEventListener('click',()=>show('recommendation','ONE CONDITION'));$('#backRecommendation').addEventListener('click',()=>show(mode==='quick'?'arrival':'recognition',mode==='quick'?'ARRIVE':'RECOGNITION'));

  function recordsForState(state){return loadSessions().filter(r=>r.state===state)}
  function resolvedForState(state){return recordsForState(state).filter(r=>Number.isFinite(r.hourScore))}
  function doseRecommendation(state){const resolved=resolvedForState(state);const quick=resolved.filter(r=>r.doseSeconds===60),full=resolved.filter(r=>r.doseSeconds>60);if(quick.length>=2&&full.length>=2){const q=avg(quick.map(r=>r.hourScore)),f=avg(full.map(r=>r.hourScore));return f>q+.35?{seconds:current.minutes*60,reason:`Your full doses averaged ${f.toFixed(1)}/5 versus ${q.toFixed(1)}/5 for quick doses.`}:{seconds:60,reason:`Your quick doses averaged ${q.toFixed(1)}/5 versus ${f.toFixed(1)}/5 for full doses.`}}return{seconds:60,reason:'Not enough comparable follow-ups yet. Quick remains the low-friction default.'}}
  function updatePersonalEvidence(){const stateRecords=recordsForState(selectedState),resolved=resolvedForState(selectedState),box=$('#personalEvidence');box.classList.remove('caution');if(!stateRecords.length){box.innerHTML='<span class="label">YOUR EVIDENCE</span><strong>STATE starts at zero.</strong><p>After a few honest sessions, this space can show patterns from your own data—not universal claims.</p>';return}
    const shift=avg(stateRecords.filter(r=>Number.isFinite(r.after)).map(r=>r.before-r.after));const hour=avg(resolved.map(r=>r.hourScore));let copy=`${stateRecords.length} similar session${stateRecords.length===1?'':'s'}`;if(shift!==null)copy+=` · immediate shift ${shift>=0?'+':''}${shift.toFixed(1)}`;if(hour!==null)copy+=` · next-hour usefulness ${hour.toFixed(1)}/5`;
    const low=resolved.length>=3&&hour<2.7;if(low)box.classList.add('caution');box.innerHTML=`<span class="label">YOUR EVIDENCE · ${resolved.length} FOLLOW-UP${resolved.length===1?'':'S'}</span><strong>${low?'This condition may not be helping enough yet.':'A personal pattern is beginning.'}</strong><p>${copy}. This is observation, not proof. ${low?'Consider choosing another state or discussing persistent difficulty with appropriate support.':''}</p>`}
  function updateFormula(){
    $('#recognitionTitle').textContent=current.recognition;$('#recognitionText').textContent=current.recognitionText;$('#sceneName').textContent=current.name;$('#sceneNumber').textContent=current.number;$('#sceneUnit').textContent=current.unit;$('#recommendTitle').textContent=current.title;$('#recommendDescription').textContent=current.description;$('#formulaName').textContent=current.name;$('#formulaNumber').textContent=current.number;$('#formulaUnit').textContent=`${current.unit} · ${current.minutes} MINUTES`;$('#fullDoseLabel').textContent=`${current.minutes} minutes`;$$('.dose-option')[1].dataset.seconds=String(current.minutes*60);$('#scienceClaim').textContent=current.science;$('#scienceSource').href=current.source;$('#practiceFormula').textContent=`${current.name} ${current.number}`;document.documentElement.style.setProperty('--accent',current.accent);document.documentElement.style.setProperty('--accent2',current.accent2);updatePersonalEvidence();const learned=doseRecommendation(selectedState);chooseDose(learned.seconds);$('#learningLimit').textContent=learned.reason+' Personal records guide the suggestion but do not establish causality or diagnosis.'
  }
  function chooseDose(seconds){selectedSeconds=seconds;$$('.dose-option').forEach(b=>b.classList.toggle('active',Number(b.dataset.seconds)===seconds));$('#beginDose').textContent=`Begin ${seconds===60?'60-second':'full'} dose →`}
  $$('.dose-option').forEach(b=>b.addEventListener('click',()=>chooseDose(Number(b.dataset.seconds))));
  const before=$('#beforeIntensity'),after=$('#afterIntensity');before.addEventListener('input',()=>$('#beforeValue').textContent=before.value);after.addEventListener('input',()=>$('#afterValue').textContent=after.value);

  async function requestWakeLock(){try{if('wakeLock' in navigator){wakeLock=await navigator.wakeLock.request('screen');$('#wakeStatus').textContent='SCREEN WAKE: ACTIVE WHILE PRACTISING';wakeLock.addEventListener('release',()=>{$('#wakeStatus').textContent='SCREEN WAKE: RELEASED'})}else $('#wakeStatus').textContent='SCREEN WAKE: NOT SUPPORTED ON THIS DEVICE'}catch{$('#wakeStatus').textContent='SCREEN WAKE: UNAVAILABLE'}}
  async function releaseWakeLock(){try{if(wakeLock)await wakeLock.release()}catch{}wakeLock=null}
  function guidance(){const elapsed=total-remaining;$('#progressRing').style.setProperty('--progress',`${Math.min(100,(elapsed/total)*100)}%`);if(current.mode==='breath'){const cycle=elapsed%10,inhale=cycle<4,phase=inhale?'inhale':'exhale';$('#practice').dataset.phase=phase;$('#phaseLabel').textContent=phase.toUpperCase();$('#phaseCount').textContent=inhale?Math.max(1,4-cycle):Math.max(1,10-cycle);$('#practiceGuidance').textContent=inhale?'Inhale gently. Do not pull in more air than feels easy.':'Exhale softly and a little longer. Let the jaw and shoulders release.';$('#practiceSub').textContent='No holds · nothing to achieve · return to natural breathing if uncomfortable';return}
    $('#practice').dataset.phase='inhale';$('#phaseLabel').textContent=current.name;$('#phaseCount').textContent=remaining;const copy={focus:'Open the exact place where the work begins. Choose only the next visible action.',release:'Notice jaw, shoulders and hands. Soften only what releases without force.',walk:'Stand up. Find daylight if available. Let the first steps happen before analysis.',courage:'Make the threshold smaller. Open it, dial it, or write the first honest line.',connect:'Choose one reasonably safe person. Write one specific, pressure-free invitation.',pause:'Name what is here in one accurate sentence. Nothing more is required.'};$('#practiceGuidance').textContent=copy[current.mode];$('#practiceSub').textContent='One finite condition · no performance · stop whenever needed'}
  function begin(){total=selectedSeconds;remaining=total;paused=false;status='active';startedAt=new Date().toISOString();currentSessionId=id();$('#practice').classList.remove('hidden');$('#practice').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';$('#practiceTime').textContent=format(remaining);$('#pauseDose').textContent='Pause';guidance();requestWakeLock();clearInterval(timer);timer=setInterval(()=>{if(paused)return;remaining--;$('#practiceTime').textContent=format(remaining);guidance();if(remaining<=0)finish('completed')},1000)}
  async function finish(nextStatus){clearInterval(timer);await releaseWakeLock();status=nextStatus;$('#practice').classList.add('hidden');$('#practice').setAttribute('aria-hidden','true');document.body.style.overflow='';const b=Number(before.value);after.value=Math.max(1,b-2);$('#afterValue').textContent=after.value;show('return','REFLECT NOW')}
  $('#beginDose').addEventListener('click',begin);$('#pauseDose').addEventListener('click',()=>{paused=!paused;$('#pauseDose').textContent=paused?'Resume gently':'Pause'});$('#completeDose').addEventListener('click',()=>finish('completed-early'));$('#exitPractice').addEventListener('click',()=>{if(confirm('End the dose and continue to an honest reflection?'))finish('exited')});

  $('#reflectionForm').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.currentTarget),finishedAt=new Date(),record={id:currentSessionId,state:selectedState,other:selectedState==='other'?$('#otherText').value.trim():'',formula:`${current.name} ${current.number}`,mode,doseSeconds:total,status,startedAt,finishedAt:finishedAt.toISOString(),timeBucket:timeBucket(finishedAt),before:Number(before.value),after:Number(after.value),nextAction:data.get('nextAction'),note:$('#note').value.trim(),followUpDueAt:new Date(finishedAt.getTime()+60*60*1000).toISOString(),hourScore:null,hourNote:'',followedUpAt:null};const items=loadSessions();items.push(record);saveSessions(items);$('#exitCopy').textContent=current.exit+' STATE will ask once, later, whether the next hour actually improved.';show('door','OPEN DOOR');toast('Saved privately. One-hour follow-up is pending.')});
  $('#leaveState').addEventListener('click',()=>{$('#final').classList.remove('hidden');document.body.style.overflow='hidden';document.title='STATE has ended — go use the hour'});

  function dueFollowup(){const now=Date.now();return loadSessions().find(r=>r.hourScore===null&&new Date(r.followUpDueAt).getTime()<=now)}
  function checkFollowup(){const item=dueFollowup();if(!item)return;pendingFollowupId=item.id;$('#followupContext').textContent=`Earlier you used ${item.formula} for ${item.state}. Rate the hour that followed—not the beauty of the exercise.`;$('#followup').classList.remove('hidden');$('#followup').setAttribute('aria-hidden','false')}
  $('#followupForm').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.currentTarget),items=loadSessions(),item=items.find(r=>r.id===pendingFollowupId);if(item){item.hourScore=Number(data.get('hourScore'));item.hourNote=$('#followupNote').value.trim();item.followedUpAt=new Date().toISOString();saveSessions(items)}$('#followup').classList.add('hidden');$('#followup').setAttribute('aria-hidden','true');pendingFollowupId=null;toast('Your next-hour result was saved privately.');renderPatterns()});
  $('#dismissFollowup').addEventListener('click',()=>{$('#followup').classList.add('hidden');$('#followup').setAttribute('aria-hidden','true');pendingFollowupId=null});

  function renderPatterns(){const items=loadSessions(),resolved=items.filter(r=>Number.isFinite(r.hourScore)),shifts=items.filter(r=>Number.isFinite(r.after)).map(r=>r.before-r.after);$('#metricSessions').textContent=items.length;$('#metricFollowups').textContent=resolved.length;$('#metricShift').textContent=shifts.length?`${avg(shifts)>=0?'+':''}${avg(shifts).toFixed(1)}`:'—';$('#metricHour').textContent=resolved.length?`${avg(resolved.map(r=>r.hourScore)).toFixed(1)}/5`:'—';const insights=[];
    if(items.length<3)insights.push(['Still learning','Fewer than three sessions means STATE should not pretend to know a personal pattern yet.']);
    const byState={};resolved.forEach(r=>(byState[r.state]??=[]).push(r));const ranked=Object.entries(byState).filter(([,v])=>v.length>=2).map(([state,v])=>({state,n:v.length,score:avg(v.map(r=>r.hourScore))})).sort((a,b)=>b.score-a.score);if(ranked[0])insights.push(['Most useful recorded condition',`${formulas[ranked[0].state].name} averaged ${ranked[0].score.toFixed(1)}/5 across ${ranked[0].n} one-hour follow-ups.`]);
    const byTime={morning:[],afternoon:[],evening:[]};resolved.forEach(r=>byTime[r.timeBucket]?.push(r.hourScore));const timeRank=Object.entries(byTime).filter(([,v])=>v.length>=2).map(([time,v])=>({time,n:v.length,score:avg(v)})).sort((a,b)=>b.score-a.score);if(timeRank[0])insights.push(['Time-of-day signal',`Recorded sessions in the ${timeRank[0].time} averaged ${timeRank[0].score.toFixed(1)}/5 across ${timeRank[0].n} follow-ups.`]);
    const quick=resolved.filter(r=>r.doseSeconds===60),full=resolved.filter(r=>r.doseSeconds>60);if(quick.length>=2&&full.length>=2)insights.push(['Dose-length comparison',`Quick doses averaged ${avg(quick.map(r=>r.hourScore)).toFixed(1)}/5; full doses averaged ${avg(full.map(r=>r.hourScore)).toFixed(1)}/5. Context may explain the difference.`]);
    if(resolved.length&&avg(resolved.map(r=>r.hourScore))<2.7)insights.push(['Important weak signal','Recent sessions have not translated into strong next-hour usefulness. STATE should not hide that.']);
    insights.push(['What this does not prove','These are self-reports without a control condition. They can guide reflection, not establish causality, efficacy or diagnosis.']);$('#insightList').innerHTML=insights.map(([title,text])=>`<article class="insight"><b>${title}</b><p>${text}</p></article>`).join('')}
  $('#openPatterns').addEventListener('click',()=>show('patterns','YOUR PATTERNS'));$('#backFromPatterns').addEventListener('click',()=>show('arrival','ARRIVE'));$$('[data-dock]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.dock,b.dataset.dock==='patterns'?'YOUR PATTERNS':'ARRIVE')));
  $('#exportData').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(loadSessions(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='state-private-sessions.json';a.click();URL.revokeObjectURL(url)});
  $('#clearData').addEventListener('click',()=>{if(confirm('Delete all STATE session records stored in this browser? This cannot be undone.')){localStorage.removeItem(STORAGE_KEY);renderPatterns();toast('Local session data deleted.')}});
  window.addEventListener('beforeunload',e=>{if(status==='active'){e.preventDefault();e.returnValue=''}});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&status==='active'&&!wakeLock)requestWakeLock()});
  renderPatterns();setTimeout(checkFollowup,450);
})();
