window.STATE_FORMULAS={
    overwhelmed:{name:'CALM',number:'10',minutes:10,unit:'GUIDED EXHALE',accent:'#9bcaff',accent2:'#d8eaff',recognition:'You do not need to solve everything from here.',recognitionText:'Let us create a little more space before deciding what comes next.',title:'Create a little more space.',description:'A gentle body-first practice using a comfortable longer exhale, sensory orientation and a clear return.',mode:'breath',science:'A comfortable longer exhale may influence breathing pace and cardiac autonomic regulation. Individual comfort matters.',source:'https://pubmed.ncbi.nlm.nih.gov/36630953/',exit:'Choose the next kind action, not the fastest reaction.'},
    scattered:{name:'FOCUS',number:'25',minutes:25,unit:'ONE VISIBLE OUTCOME',accent:'#ef8062',accent2:'#f6c9ba',recognition:'Your attention may need fewer doors, not more motivation.',recognitionText:'We will make one useful action more visible than the surrounding noise.',title:'Make one outcome visible.',description:'A finite focus room that names one observable result and removes unnecessary exits.',mode:'focus',science:'Reducing task scope and external distractions are behavioural mechanisms. STATE does not claim to read attention networks.',source:'../docs/v6-source-standard.md',exit:'Open the exact place where the next useful action begins.'},
    tense:{name:'RELEASE',number:'05',minutes:5,unit:'BODY SOFTENING',accent:'#ee785f',accent2:'#f5c7b9',recognition:'Your body may be carrying the conversation for you.',recognitionText:'Before asking the mind for answers, let the muscles receive a different message.',title:'Let the body put something down.',description:'A gentle sequence for jaw, shoulders, hands and breath—without forcing relaxation.',mode:'release',science:'Voluntary awareness and release may change perceived tension. STATE does not measure muscle activity or clinical symptoms.',source:'../docs/v6-source-standard.md',exit:'Carry less unnecessary effort into the next moment.'},
    flat:{name:'WALK',number:'20',minutes:20,unit:'MOVEMENT + PERSPECTIVE',accent:'#9ed0a8',accent2:'#d8eadc',recognition:'You may not need a better thought before you move.',recognitionText:'Let light, rhythm and a changing horizon meet you outside the screen.',title:'Let the world move around you.',description:'An outdoor walking ritual combining movement, visual distance and a deliberate break from fixation.',mode:'walk',science:'Walking combines physical activity, changing sensory input and environmental context. Effects depend on duration, setting and the person.',source:'../docs/v6-source-standard.md',exit:'Stand up, find daylight if available, and let the first steps happen.'},
    avoidant:{name:'COURAGE',number:'01',minutes:15,unit:'ONE BRAVE ACT',accent:'#c7b7ff',accent2:'#e7e0ff',recognition:'Fear does not need to disappear before action begins.',recognitionText:'We will shrink the threshold until the first honest movement fits inside this minute.',title:'Cross one visible threshold.',description:'A tiny-action ritual for beginning the necessary thing while fear is still present.',mode:'courage',science:'Approach behaviour can reduce avoidance over time, but safety, consent and context determine whether an action is appropriate.',source:'../docs/v6-source-standard.md',exit:'Let the completed first step remain real.'},
    lonely:{name:'CONNECT',number:'02',minutes:20,unit:'TWO REAL QUESTIONS',accent:'#e9ca6d',accent2:'#f6eac0',recognition:'Longing for connection is not a personal defect.',recognitionText:'Let us make one safe bridge toward another person—not an audience.',title:'Make one safe bridge.',description:'A consent-based invitation into honest attention, two real questions and listening without immediately fixing.',mode:'connect',science:'Perceived support and responsive listening are associated with wellbeing; this ritual cannot guarantee safety or repair.',source:'../docs/v6-source-standard.md',exit:'Choose one reasonably safe person and one pressure-free invitation.'},
    other:{name:'PAUSE',number:'02',minutes:2,unit:'NAME WHAT IS HERE',accent:'#b9c4ce',accent2:'#e1e6e9',recognition:'Not everything needs to fit a predefined label.',recognitionText:'We can begin by naming what is here without immediately turning it into a problem to solve.',title:'Give the experience a little shape.',description:'A short pause to name the present state, notice the body and choose one gentle next action.',mode:'pause',science:'Naming and describing experience can support reflection. STATE does not promise a fixed emotional reduction.',source:'../docs/v6-source-standard.md',exit:'Let one accurate sentence be enough for now.'}
  };
