const formulas={focus:{name:'FOCUS 25',description:'A finite room for moving one visible task from resistance into motion.',minutes:25,modes:['solo']},calm:{name:'CALM 10',description:'A body-first reset for lowering intensity before choosing what comes next.',minutes:10,modes:['solo']},courage:{name:'COURAGE 01',description:'A tiny-action ritual for doing the necessary thing while fear is still present.',minutes:15,modes:['solo']},connection:{name:'TWO QUESTIONS',description:'A guided conversation that makes it safer to be known and to listen.',minutes:20,modes:['together']},purpose:{name:'ONE GOOD DEED',description:'A service ritual that turns care into one completed useful action.',minutes:30,modes:['service']}};
const toast=message=>{const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>el.classList.remove('show'),2600)};
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const art=document.getElementById('heroArt'),pack=document.getElementById('heroPack');art?.addEventListener('pointermove',event=>{const rect=art.getBoundingClientRect(),x=(event.clientX-rect.left)/rect.width-.5,y=(event.clientY-rect.top)/rect.height-.5;pack.style.transform=`rotate(5deg) rotateY(${x*18-8}deg) rotateX(${-y*12}deg)`});art?.addEventListener('pointerleave',()=>pack.style.transform='rotate(5deg) rotateY(-8deg)');
function recommend(){const need=document.getElementById('need').value,data=new FormData(document.getElementById('dispensaryForm')),time=Number(data.get('time')),mode=data.get('mode');let key=need;if(mode==='together')key='connection';if(mode==='service')key='purpose';if(time<=10&&key!=='calm')key='calm';const formula=formulas[key];document.getElementById('resultName').textContent=formula.name;document.getElementById('resultDescription').textContent=formula.description;document.getElementById('resultPill').textContent=`${formula.minutes} minutes · ${formula.modes[0]}`;document.getElementById('beginRecommended').dataset.dose=formula.name}
document.getElementById('dispensaryForm').addEventListener('submit',event=>{event.preventDefault();recommend()});document.getElementById('need').addEventListener('change',recommend);document.querySelectorAll('#dispensaryForm input').forEach(input=>input.addEventListener('change',recommend));
document.querySelectorAll('[data-dose],#beginRecommended').forEach(button=>button.addEventListener('click',()=>{const name=button.dataset.dose||document.getElementById('resultName').textContent;toast(`${name} preview queued. The full formula ships after its evidence gate.`)}));
document.querySelectorAll('[data-buy]').forEach(button=>button.addEventListener('click',()=>toast('Checkout remains intentionally disabled until the ledger and formulas are real.')));
const modal=document.getElementById('giftModal');document.querySelectorAll('[data-open-gift]').forEach(button=>button.addEventListener('click',()=>modal.classList.add('open')));document.querySelectorAll('[data-close-modal]').forEach(button=>button.addEventListener('click',()=>modal.classList.remove('open')));modal.addEventListener('click',event=>{if(event.target===modal)modal.classList.remove('open')});document.getElementById('createGift').addEventListener('click',()=>{const name=document.getElementById('giftName').value.trim()||'someone';toast(`Prototype gift created for ${name}. No payment or donation recorded.`);modal.classList.remove('open')});
let ledger={purchased:0,funded:0,allocated:0,redeemed:0};document.getElementById('simulatePurchase').addEventListener('click',()=>{ledger.purchased+=1;ledger.funded+=1;document.getElementById('packsPurchased').textContent=ledger.purchased;document.getElementById('accessFunded').textContent=ledger.funded;toast('Prototype event only: one purchase and one funded access added locally.')});recommend();
